name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/src/**'

jobs:
  web-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Sync files via SFTP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "frontend/src/*"
        target: "domains/divinosgraffic.co.mz/public_html"
        strip_components: 2
