name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/src/**'

jobs:
  web-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/src/
        server-dir: ./public_html/
